name: SporeMods

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: microsoft/setup-msbuild@v2
      - name: Install Dependencies
        run: |
          choco install 7zip -r -y
      - name: Build Spore-ModAPI
        run: |
          cd "SporeMods\Spore-ModAPI\Spore ModAPI"
          msbuild /m /p:Configuration=Release /p:Platform=x86
          msbuild /m /t:BuildDlls /p:BuildVer=180 /p:Config=Release /p:Platform=x86
      - name: Build SporeServer
        run: |
          cd SporeMods\SporeServer
          msbuild /m /p:Configuration=Release /p:Platform=x86
      - name: Create SporeServer.sporemod
        run: |
          cd SporeMods
          .\CreateSporeMod.bat
      - uses: actions/upload-artifact@v4
        with:
          name: SporeServer.sporemod
          path: SporeMods/bin/SporeServer.sporemod
