name: SporeServer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: |
        dotnet restore /p:Configuration="Debug (.NET)"
    - name: Build
      run: |
        dotnet build --no-restore /p:Configuration="Debug (.NET)"
    - name: Test
      run: |
        dotnet test /p:Configuration="Debug (.NET)"
