name: SporeServer

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet restore /p:Configuration="Debug (.NET)"
    - name: Build
      run: |
        dotnet build --no-restore /p:Configuration="Debug (.NET)"
    - name: Test
      run: |
        dotnet test /p:Configuration="Debug (.NET)"
